export const SEARCH_STADIUMS ='SEARCH_STADIUMS';
export const SEARCH_STADIUMS_SUCCESS ='SEARCH_STADIUMS_SUCCESS';
export const SEARCH_STADIUM_DETAIL = 'SEARCH_STADIUM_DETAIL';

export const SEARCH_STADIUM_BY_ID = 'SEARCH_STADIUM_BY_ID';
export const SEARCH_STADIUM_BY_ID_SUCCESS = 'SEARCH_STADIUM_BY_ID_SUCCESS';
export const SEARCH_STADIUM_BY_ID_ERROR = 'SEARCH_STADIUM_BY_ID_ERROR';

export const ADD_STADIUM_ACCTION = 'ADD_STADIUM_ACCTION'
export const ADD_STADIUM_ACCTION_SUCCESS = 'ADD_STADIUM_ACCTION_SUCCESS'
export const ADD_STADIUM_ACCTION_ERROR = 'ADD_STADIUM_ACCTION_ERROR'